Codebook for Getting and Cleaning Data Project
========================================================

This codebook provides information about the variables contained in the tidy dataset generated by the R code that was written for the project. My tidy dataset contained 81 columns, which corresponds to 79 variables (81 minus the 2 columns that contain the subject IDs and Activity Codes). See the README for more information regarding how it was determined which variables were applicable. The variables in the dataset are as follows:

## Time Domain Variables

The prefix "time" was used to identify time domain variables. Information regarding sample rates and filtering can be found in the features_info.txt file. The variables below represent both raw tri-axial (x,y,z) data collected from the accelerometers and gyros as well as parsed/calculated data for gravity, jerk, and magnitude. As stated in the project desription, only variables for which averages (mean) and standard deviations (std) were considered.

The variables are meant to be human readable. For example, timebodyaccmeanx corresponds to the mean of the x-axis output of the body accelerometer in the time domain. Please apply the same logic when parsing the rest of the variable names. The variable names are provided in all lower case as prescribed by the course directions, even though Camel case seems to be more readable.
                      
"timebodyaccmeanx"                
"timebodyaccmeany"               
"timebodyaccmeanz"                
"timegravityaccmeanx"            
"timegravityaccmeany"             
"timegravityaccmeanz"            
"timebodyaccjerkmeanx"            
"timebodyaccjerkmeany"           
"timebodyaccjerkmeanz"            
"timebodygyromeanx"              
"timebodygyromeany"               
"timebodygyromeanz"              
"timebodygyrojerkmeanx"           
"timebodygyrojerkmeany"          
"timebodygyrojerkmeanz"           
"timebodyaccmagmean"             
"timegravityaccmagmean"           
"timebodyaccjerkmagmean"         
"timebodygyromagmean"             
"timebodygyrojerkmagmean"  
"timebodyaccstdx"                 
"timebodyaccstdy"                
"timebodyaccstdz"                 
"timegravityaccstdx"             
"timegravityaccstdy"              
"timegravityaccstdz"             
"timebodyaccjerkstdx"             
"timebodyaccjerkstdy"            
"timebodyaccjerkstdz"             
"timebodygyrostdx"               
"timebodygyrostdy"                
"timebodygyrostdz"               
"timebodygyrojerkstdx"            
"timebodygyrojerkstdy"           
"timebodygyrojerkstdz"            
"timebodyaccmagstd"              
"timegravityaccmagstd"            
"timebodyaccjerkmagstd"          
"timebodygyromagstd"              
"timebodygyrojerkmagstd"

## Frequency Domain Variables

The variable names for the following variables follow similar logic to that provided for the time domain variables. The time domain variables were subjected to the Fast Fourier Transform (FFT) to generate data in the frequency domain. The prefix "freq" was used to identify frequency domain variable. Please note that the tidy data set is not sorted in such a way that the time/frequency domain variables are separated, but it was decided to do so in the codebook for clarity. 

"freqbodyaccmeanx"                
"freqbodyaccmeany"               
"freqbodyaccmeanz"                
"freqbodyaccmeanfreqx"           
"freqbodyaccmeanfreqy"            
"freqbodyaccmeanfreqz"           
"freqbodyaccjerkmeanx"            
"freqbodyaccjerkmeany"           
"freqbodyaccjerkmeanz"            
"freqbodyaccjerkmeanfreqx"       
"freqbodyaccjerkmeanfreqy"        
"freqbodyaccjerkmeanfreqz"       
"freqbodygyromeanx"               
"freqbodygyromeany"              
"freqbodygyromeanz"               
"freqbodygyromeanfreqx"          
"freqbodygyromeanfreqy"           
"freqbodygyromeanfreqz"          
"freqbodyaccmagmean"              
"freqbodyaccmagmeanfreq"         
"freqbodybodyaccjerkmagmean"      
"freqbodybodyaccjerkmagmeanfreq" 
"freqbodybodygyromagmean"         
"freqbodybodygyromagmeanfreq"    
"freqbodybodygyrojerkmagmean"     
"freqbodybodygyrojerkmagmeanfreq"
"freqbodyaccstdx"                 
"freqbodyaccstdy"                
"freqbodyaccstdz"                 
"freqbodyaccjerkstdx"            
"freqbodyaccjerkstdy"             
"freqbodyaccjerkstdz"            
"freqbodygyrostdx"                
"freqbodygyrostdy"               
"freqbodygyrostdz"                
"freqbodyaccmagstd"              
"freqbodybodyaccjerkmagstd"       
"freqbodybodygyromagstd"         
"freqbodybodygyrojerkmagstd"

